// VIEWS
export const DISPLAY_SELECT_ACTION = 'DISPLAY_SELECT_ACTION';
export const DISPLAY_SELECT_ACTION_SUCCESS = 'DISPLAY_SELECT_ACTION_SUCCESS';
export const DISPLAY_SELECT_ACTION_FAILURE = 'DISPLAY_SELECT_ACTION_FAILURE';

export const DISPLAY_REPORT_INCIDENT = 'DISPLAY_REPORT_INCIDENT';
export const DISPLAY_REPORT_INCIDENT_SUCCESS = 'DISPLAY_REPORT_INCIDENT_SUCCESS';
export const DISPLAY_REPORT_INCIDENT_FAILURE = 'DISPLAY_REPORT_INCIDENT_FAILURE';

export const DISPLAY_VIEW_REPORTS = 'DISPLAY_VIEW_REPORTS';
export const DISPLAY_VIEW_REPORTS_SUCCESS = 'DISPLAY_VIEW_REPORTS_SUCCESS';
export const DISPLAY_VIEW_REPORTS_FAILURE = 'DISPLAY_VIEW_REPORTS_FAILURE';

// MAP


// REPORT INCIDENT FORM


// DB