// MAP

export const MAP_IS_LOADING = "MAP_IS_LOADING";

// CURRENT LOCATION

export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const SET_CURRENT_LOCATION_SUCCESS = "SET_CURRENT_LOCATION_SUCCESS";
export const SET_CURRENT_LOCATION_FAILURE = "SET_CURRENT_LOCATION_FAILURE";

// CENTER MARKER

export const MOVE_CENTER = "MOVE_CENTER";
export const CENTER_MOVED_SUCCESS = "CENTER_MOVED_SUCCESS";
export const CENTER_MOVED_FAILURE = "CENTER_MOVED_FAILURE";

// ADDRESS

export const SET_ADDRESS = "SET_ADDRESS";
export const ADDRESS_IS_LOADING = "ADDRESS_IS_LOADING";
export const SET_ADDRESS_SUCCESS = "SET_ADDRESS_SUCCESS";
export const SET_ADDRESS_FAILURE = "SET_ADDRESS_FAILURE";

// REPORT FORM

export const SUBMIT_FORM = "SUBMIT_FORM";
export const SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS";
export const SUBMIT_FORM_FAILURE = "SUBMIT_FORM_FAILURE";

// RADIO SCALE

export const SELECTED_RATING = "SELECTED_RATING";

// VIEWS

// INCIDENT REPORTS

export const GET_INCIDENTS = "GET_INCIDENTS";
export const GET_INCIDENTS_SUCCESS = "GET_INCIDENTS_SUCCESS";
export const GET_INCIDENTS_FAILURE = "GET_INCIDENTS_FAILURE";
